- name: Copy Custom-SSL Certificate
  copy: 
    content: "{{ item.crt }}"
    dest: "/etc/ssl/certs{{ item.name }}.crt"
    owner: root
    group: root
  with_items: "{{ nginx_revproxy_upload_ssl_certiciate }}"
  notify:
    - Reload Nginx

- name: Copy Custom-SSL Key
  copy: 
    content: "{{ item.key }}"
    dest: "/etc/ssl/certs{{ item.name }}.key"
    owner: root
    group: root
  with_items: "{{ nginx_revproxy_upload_ssl_certiciate }}"
  notify:
    - Reload Nginx